### PR TITLE
don't open meshcat (automatically) in exercises

### PR DESCRIPTION
**Pull request by RussTedrake**
if we really want this as the default behavior, then it needs to be guarded with "if running_as_notebook".  as it is, every time I run the bazel tests, it tries to open windows (and fails, because by the time the window is opened the test has finished).

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/50)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+@hjsuh94 for review, please.

**Review by hjsuh94 — COMMENTED** [review]
I agree with the change - it will coincidentally make Gradescope messages a lot cleaner :) 

A minor thing: we shouldn't edit the exercises directory directly since they always get overwritten from the solutions repo. The right workflow should be pushing to `manipulation-solutions', calling the `install.py` script from there, and then PRing (or pushing) to this repo.  

We can either close this PR, and I can submit another one after making changes to the solutions repo, or you can revise this PR to be consistent with the solutions repo? 

> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/50#-:-MIAgptSBDT8qwPtoYL3:b-59ym4q)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by RussTedrake** [comment]
oops!  I forgot about that (ironic, since I was the one who set that workflow up in the first place).  If you don't mind doing the change to solutions, that would be great.  I can close this or use it, whichever you prefer.

**Comment by hjsuh94** [comment]
Replaced with #52

**Pull request closed without merging**
