### PR TITLE
Update analytic_grasp test cases

### PR DESCRIPTION
**Pull request by qujohn314**
- **Changed Analytic antipodal grasp notebook + autograder.**
"The test should be rewritten to be testing the antipodality, not the numerical equivalence to one particular solution."

1. First finds the proposed antipodal points given by 'find_antipodal_pts()'. 
2. Compute tangent vector for each point.
3. Compute the normal vector for each point.
4. Assert normals are pointing in exactly opposite directions.

- **Changed location of points in compute sdf problem**

Associated solutions PRs:
- https://github.com/RobotLocomotion/manipulation-solutions/pull/85
- https://github.com/RobotLocomotion/manipulation-solutions/pull/86
- https://github.com/RobotLocomotion/manipulation-solutions/pull/87

- - -
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/357)

### CODE REVIEW

**Comment by thatprogrammer1** [comment]
You should install the pre-commit hooks to automatically lint. https://github.com/RussTedrake/manipulation/blob/master/Developers.md#please-install-the-pre-commit-hooks

**Review by nepfaff — CHANGES_REQUESTED** [review]
The linter is failing. Please install pre-commit or run the tests locally to identify the issues.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/357#-:-O837xm89OPlGlp1B3AQ:b-ltuc36)* status: all files reviewed, 1 unresolved discussion (waiting on @qujohn314)

___
*[`manipulation/exercises/clutter/test_analytic_grasp.py` line 49 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/357#-O838YrX0vjkBf2fZyV0:-O838YrX0vjkBf2fZyV1:bzbe37d) ([raw file](https://github.com/RussTedrake/manipulation/blob/a84b10ee54e1479bc9b2edb5542aee3b6c38db39/manipulation/exercises/clutter/test_analytic_grasp.py#L49)):*
> ```Python
>             n_2 = -np.array([-v_2[1], v_2[0]])
> 
>             # yapf: enable
> ```

What is this for?

**Comment by qujohn314** [comment]
#ypaf: enable/disable was left over from the previous autograder code. I can remove it.

**Comment by nepfaff** [comment]
> #ypaf: enable/disable was left over from the previous autograder code. I can remove it.

Please do. I had a look and it looks like we have a bunch of this mess in some notebooks even though we use `black` as the formatter...

**Comment by qujohn314** [comment]
Passing lint, now I am not really sure why I am failing the current test that I am. 

I tried running 'python3 htmlbook/install_html_meta_data.py' from the book directory, but wasn't able to do so. 
image

**Comment by nepfaff** [comment]
> install_html_meta_data

From that message, it looks like you're missing `mysql` package. Try pip installing that and any other packages that it complains about.

**Review by nepfaff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/357)* status: all files reviewed, 1 unresolved discussion (waiting on @qujohn314)

___
*[`manipulation/exercises/clutter/test_analytic_grasp.py` line 21 at r2](https://reviewable.io/reviews/RussTedrake/manipulation/357#-O86HkAL7_NErOXeTyGM:-O86HkAL7_NErOXeTyGN:bqfphnb) ([raw file](https://github.com/RussTedrake/manipulation/blob/1b2f7787974fb8adecec9618bb5fb4533fcee31d/manipulation/exercises/clutter/test_analytic_grasp.py#L21)):*
> ```Python
>         f = self.notebook_locals["find_antipodal_pts"]
> 
>         np.random.seed(55)
> ```

Do we need a seed after the changes?

**Comment by qujohn314** [comment]
> > install_html_meta_data
> 
> From that message, it looks like you're missing the `mysql` package. Try pip installing that and any other packages that it complains about.

I tried pip installing it, but still got the same problem. Weird that I am just now failing these test cases. The previous commits were only failing lint.

**Comment by nepfaff** [comment]
It works on my side. I can fix it and push it for you but it looks like a can't do this as you're opening this PR from your master rather than from a branch. Happy to help with this if you change the PR to be from a branch.

Note that for me it worked with pip installing `mysql`.

**Comment by nepfaff** [comment]
These tests are failing because they refer to dynamic references, so more about timing of this PR than anything else.

**Comment by qujohn314** [comment]
Should I close this PR and make a new one?

**Review by nepfaff — CHANGES_REQUESTED** [review]
Looks good. The last thing missing is syncing the changes from https://github.com/RobotLocomotion/manipulation-solutions/pull/85 and https://github.com/RobotLocomotion/manipulation-solutions/pull/87 using the `install.py` script.
This requires https://github.com/RobotLocomotion/manipulation-solutions/pull/87 to be complete.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/357#-:-O8BZthbB4s3DAryCkaj:b6dy0fc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @qujohn314)

**Comment by nepfaff** [comment]
Replaced by https://github.com/RussTedrake/manipulation/pull/358

**Pull request closed without merging**
