### PR TITLE
notebook commits for set 4

### PR DESCRIPTION
**Pull request by hjsuh94**
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45)

### CODE REVIEW

**Comment by RussTedrake** [comment]
___
*[exercises/pose/ransac.ipynb, line 43 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuzfWP8saHpfi11SAC:-MHuzfWP8saHpfi11SAD:bkcoa0l) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/ransac.ipynb#L43)):*
> ```
>     "import matplotlib.pyplot as plt, mpld3\n",
>     "from IPython.display import HTML, display\n",
>     "import tarfile \n",
> ```

don't need this anymore?

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45)* status: all files reviewed, 5 unresolved discussions (waiting on @hjsuh94)

___
*[exercises/pose/BUILD.bazel, line 24 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuz-o15ZwNFAL-FxIC:-MHuz-o15ZwNFAL-FxID:b-36du16) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/BUILD.bazel#L24)):*
> ```Starlark
>         "//manipulation/exercises/pose:test_ransac",
>     ],
>     srcs = ["ransac.ipynb"],
> ```

this and the one above should need to reference the bunny file as data?
i don't think bazel tests will work without it..?
___
*[exercises/pose/bunny_icp.ipynb, line 51 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuzlHt5YRtpRRBj935:-MHuzlHt5YRtpRRBj936:b-qu7r5h) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/bunny_icp.ipynb#L51)):*
> ```
>     "import matplotlib.pyplot as plt, mpld3\n",
>     "from IPython.display import HTML, display\n",
>     "import tarfile \n",
> ```

don't need this anymore?
___
*[exercises/pose/bunny_icp.ipynb, line 53 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuz9-464MyDGVT_Yi-:-MHuz9-464MyDGVT_Yi0:bgh9qzh) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/bunny_icp.ipynb#L53)):*
> ```
>     "import tarfile \n",
>     "\n",
>     "# Install pyngrok.\n",
> ```

that comment is not true anymore
___
*[exercises/pose/ransac.ipynb, line 45 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuzqPF69-VDtUXQ3c6:-MHuzqPF69-VDtUXQ3c7:b-4jgw71) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/ransac.ipynb#L45)):*
> ```
>     "import tarfile \n",
>     "\n",
>     "# Install pyngrok.\n",
> ```

no longer true.

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @RussTedrake)

___
*[exercises/pose/BUILD.bazel, line 24 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuz-o15ZwNFAL-FxIC:-MHv2zdK97wbqPrthxZd:bs7wumx) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/BUILD.bazel#L24)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this and the one above should need to reference the bunny file as data?
i don't think bazel tests will work without it..?
</blockquote></details>

Done. 
___
*[exercises/pose/bunny_icp.ipynb, line 51 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuzlHt5YRtpRRBj935:-MHv34_q3DizWfib5pdb:bs7wumx) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/bunny_icp.ipynb#L51)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

don't need this anymore?
</blockquote></details>

Done. 
___
*[exercises/pose/bunny_icp.ipynb, line 53 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuz9-464MyDGVT_Yi-:-MHv35Sy6GFoxR19QZNL:bs7wumx) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/bunny_icp.ipynb#L53)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

that comment is not true anymore
</blockquote></details>

Done. 
___
*[exercises/pose/ransac.ipynb, line 43 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuzfWP8saHpfi11SAC:-MHv36Rh8e0FLIsFRExS:b-896fix) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/ransac.ipynb#L43)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

don't need this anymore? 
</blockquote></details>

Done.
___
*[exercises/pose/ransac.ipynb, line 45 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHuzqPF69-VDtUXQ3c6:-MHv370OD-8FwmY1TzZA:bs7wumx) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/ransac.ipynb#L45)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

no longer true.
</blockquote></details>

Done.

**Review by RussTedrake — APPROVED** [review]
:lgtm:  just waiting on CI.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45#-:-MHv4WQ28vd_0WIIeTAH:bneom0t)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[exercises/pose/pose_estimation_icp.ipynb, line 53 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHva41bBwwR8_WQe-ze:-MHva41c6_lP7syP0ILx:b-c5i0u1) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/pose_estimation_icp.ipynb#L53)):*
> ```
>     "# Setup rendering (with xvfb), if necessary:\n",
>     "import os\n",
>     "if 'google.colab' in sys.modules and os.getenv(\"DISPLAY\") is None:\n",
> ```

i think you want to keep this...?  CI should be ok without it.

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45)* status: all files reviewed, 1 unresolved discussion (waiting on @RussTedrake)

___
*[exercises/pose/pose_estimation_icp.ipynb, line 53 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHva41bBwwR8_WQe-ze:-MHvbVtl24Maz_n8DPfD:b-om6b8v) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/pose_estimation_icp.ipynb#L53)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think you want to keep this...?  CI should be ok without it.
</blockquote></details>

CI is okay but it didn't work for Gradescope since it had no `DISPLAY`, yet was not running Colab. 

We could change it to an `or` between Colab and display, or just have the display (as is). I confirmed Colab will still behave the same even if there's no `google.colab in sys.modules` line.

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @RussTedrake)

___
*[exercises/pose/pose_estimation_icp.ipynb, line 53 at r1](https://reviewable.io/reviews/russtedrake/manipulation/45#-MHva41bBwwR8_WQe-ze:-MHw0UZLE0D7A_UQE8qQ:b-896fix) ([raw file](https://github.com/russtedrake/manipulation/blob/d6b94f811df8d4110a5fc3e3ea4cd5ebee6663e0/exercises/pose/pose_estimation_icp.ipynb#L53)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

CI is okay but it didn't work for Gradescope since it had no `DISPLAY`, yet was not running Colab. 

We could change it to an `or` between Colab and display, or just have the display (as is). I confirmed Colab will still behave the same even if there's no `google.colab in sys.modules` line. 
</blockquote></details>

Done.

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/45#-:-MHw1VeH9gEV-3zH-zVx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
