### PR TITLE
remove survey from reflected inertia problem

### PR DESCRIPTION
**Pull request by hjsuh94**
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/33)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/33)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[exercises/robot/reflected_inertia.ipynb, line 46 at r1](https://reviewable.io/reviews/russtedrake/manipulation/33#-MHEDiIMEhXzZ39aqjQl:-MHEDiIMEhXzZ39aqjQm:b5a0t4k) ([raw file](https://github.com/russtedrake/manipulation/blob/cb95d5f058b0d13542d173826c19d4be5f67402f/exercises/robot/reflected_inertia.ipynb#L46)):*
> ```
>     "    from setup_manipulation_colab import setup_manipulation\n",
>     "    setup_manipulation(manipulation_sha='d117f1b74d9f123c5374ed0baf81fba77b1eb572', drake_version='20200831', drake_build='nightly')\n",
>     "    !pip install mpld3"
> ```

not sure you wanted this to sneak in?

**Comment by hjsuh94** [comment]
Makes sense - I've bumped up the sha to the recent version and got rid of `!pip install mpld3` and `!pip install pyngrok` from both assignments.

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/33)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hjsuh94 and @RussTedrake)

___
*[exercises/robot/reflected_inertia.ipynb, line 70 at r2](https://reviewable.io/reviews/russtedrake/manipulation/33#-MHGrVzRAiOl18eyla6g:-MHGrVzS4RZtQSpAuBNO:b32c3mu) ([raw file](https://github.com/russtedrake/manipulation/blob/0dffdfb38e27c9448598b13b71efe845eea8f83d/exercises/robot/reflected_inertia.ipynb#L70)):*
> ```
>     "\n",
>     "# enable mpld3 notebook\n",
>     "if 'google.colab' in sys.modules:\n",
> ```

you've also reverted my fix on the left... you want to call mpld3.enable whenever we are running as notebook (not just on colab).  sorry i didn't notice that before!

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/33)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hjsuh94 and @RussTedrake)

___
*[exercises/robot/reflected_inertia.ipynb, line 70 at r2](https://reviewable.io/reviews/russtedrake/manipulation/33#-MHGrVzRAiOl18eyla6g:-MHGrs1811SLPZ-uzuev:b-hoaqf2) ([raw file](https://github.com/russtedrake/manipulation/blob/0dffdfb38e27c9448598b13b71efe845eea8f83d/exercises/robot/reflected_inertia.ipynb#L70)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

you've also reverted my fix on the left... you want to call mpld3.enable whenever we are running as notebook (not just on colab).  sorry i didn't notice that before!
</blockquote></details>

(on the left, when you view this in reviewable)

**Comment by hjsuh94** [comment]
I've added them back in! 

We should not edit files in `exercises` directly since they get overwritten from the solutions repo upon calling `install.py` - I updated the solutions repo with the lines as well.

**Comment by hjsuh94** [comment]
Just added another commit to fix some typos in the planar manipulator problem. 

Updated the `enable mpdl3` line with the new syntax while I'm at it!

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/33#-:-MHJCjglDCWNnmwL_Wrr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

**Pull request merged**
