### PR TITLE
Start replacing cmake/ctest with bazel

### PR DESCRIPTION
**Pull request by RussTedrake**
but i'm having trouble with the drake resource path.  
```
bazel run //src/depth_camera_demo:show_camera
```
fails to find the resource.  but running this test from python, or ctest, works fine.  

but I don't think either my console nor my cmake environment are setting `DRAKE_RESOURCE_ROOT`.  So I'm not actually sure how those resources are being found in the nominal cases.  the `set_log_level(trace)` was not helpful.

The most obvious difference I see in the configurations is that I believe the drake install path is being added to my PYTHONPATH for cmake and in my console, but not in bazel.  But adding that directory as an `import` statement in the `BUILD.bazel` file did not work (yet).

Any suggestions @jamiesnape , @jwnimmer-tri, @EricCousineau-TRI ?

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
I don't know that we have an example of using the prebuilt Drake from Bazel?

I think the way to do it would be roughly:

WORKSPACE
```python
new_local_repository(
    name = "drake",
    path = "/Users/russt/drake-install",
    build_file = "drake.BUILD.bazel",
)
```

drake.BUILD.bazel
```
py_library(
    name = "pydrake"
    srcs = glob(["**/*.py"]),
    data = glob(["lib/**", "share/**"], excludes=["**/*.py"]),
)
```

Do you think you'll stick with using the prebuilt?  I think we could put together a https://github.com/RobotLocomotion/drake-external-examples prototype of `drake_bazel_installed` pretty quickly to help, if so.

**Comment by RussTedrake** [comment]
Thanks!
My personal workflow is basically always using my local drake clone, which i install manually using the bazel install target in drake.
And the workflow i’ve always recommended for class has been to grab the precompiled binaries.  http://manipulation.csail.mit.edu/text/manipulation.html?chapter=drake

If there is a different workflow you’d recommend then i’m happy to update.  But i am currently of the opinion that, for most users that find their way to the course notes, grabbing precompiled drake and running these minimal python-only examples is preferred over the alternatives (everyone compiles drake or must use docker).  The biggest downside is that this still has them installing a bunch of system dependencies.

**Comment by jamiesnape** [comment]
I guess what is the motivation for changing? Running (interactive) python scripts is generally going to be easier from an install tree.

Otherwise, I think we need to work on an easier way for people to use the prebuilt from within Bazel, and I don't think putting something in `drake-external-examples` is going to keep up with the various compiler flags needed.

**Comment by jamiesnape** [comment]
(i.e, maybe we either embed a `BUILD` file somewhere or write `.pc` files)

**Comment by RussTedrake** [comment]
Motivation for changing -- i am not building anything, only running python (and lint) scripts as test.  I think the `bazel test` workflow is far better than the `ctest` workflow.  I've had a TODO for myself to switch the underactuated repo over for a while, too.

**Comment by jamiesnape** [comment]
Fair enough, but I think we should do some work at the Drake end to make this basically trivial at your end.

**Comment by jwnimmer-tri** [comment]
I will put up a `drake_external_examples` PR to show what this currently looks like with no changes to Drake, and then we can iterate between that and Drake to close the convenience gap.

**Comment by jamiesnape** [comment]
FWIW, I see something like embedding:

`WORKSPACE`:
```
workspace(name = drake)
```

`BUILD`:
```
py_library(name = "pydrake")
```
into the install tree to start. Then adding `cc_library(name = "drake")` and a `py_binary` for each runnable example.

**Comment by RussTedrake** [comment]
Thank you both.  I'm happy to be patient and do this right.

**Comment by RussTedrake** [comment]
I’d love to keep making progress on this.  Might I ask where things stand?  Should we be moving @jwnimmer-tri ‘s draft PR forward?

**Comment by jwnimmer-tri** [comment]
I'll take a look at my PRs and try to at least post (over there) a list of remaining work before they are ready for full review.

**Comment by jwnimmer-tri** [comment]
The https://github.com/RobotLocomotion/drake-external-examples/tree/master/drake_bazel_installed is now on master, and provides a starting point.  Note that `@drake//bindings/pydrake` is the only target available for now.

**Pull request merged**
