### PR TITLE
Add Behavior Trees exercise

### PR DESCRIPTION
**Pull request by rachelholladay**
From our previous discussion I corrected the big typo and made a few wording adjustments. More adjustments / modifications are welcome. 

Naive question: in the hybrid latex/html that the textbook is written in, how do I reference a figure? (I dug around but couldn't figure it out) Right now I hard coded a reference, but thats obviously a bad idea.

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/170)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/170)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @rachelholladay and @RussTedrake)

___
*[clutter.html, line 858 at r1](https://reviewable.io/reviews/russtedrake/manipulation/170#-MlwBgij2FygGZbKZ024:-MlwBgij2FygGZbKZ025:b-ikrob5) ([raw file](https://github.com/russtedrake/manipulation/blob/bbc6afded185ccba7d73e0f06f303a5ffbe74910/clutter.html#L858)):*
> ```HTML
> 
> </li><br>
> <li id=Colledanchise18>
> ```

my guess is that you ran this manually?  you're not going to believe it, but there is automation for this....

The bibtex engine is here:
https://groups.csail.mit.edu/robotics-center/elib/search.cgi?q=%s&s=0
and once you add it you have to run `python3 htmlbook/install_html_metadata.py` .  (if you run the bazel tests, it will complain at you and tell you what to run).

**Comment by RussTedrake** [comment]
___
*[clutter.html, line 858 at r1](https://reviewable.io/reviews/russtedrake/manipulation/170#-MlwBgij2FygGZbKZ024:-MlwCNTjEC3naRQ4FLdv:brwzcem) ([raw file](https://github.com/russtedrake/manipulation/blob/bbc6afded185ccba7d73e0f06f303a5ffbe74910/clutter.html#L858)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

my guess is that you ran this manually?  you're not going to believe it, but there is automation for this....

The bibtex engine is here:
https://groups.csail.mit.edu/robotics-center/elib/search.cgi?q=%s&s=0
and once you add it you have to run `python3 htmlbook/install_html_metadata.py` .  (if you run the bazel tests, it will complain at you and tell you what to run).  
</blockquote></details>

"ran this manually" => "entered this manually"

**Comment by RussTedrake** [comment]
___
*[clutter.html, line 858 at r1](https://reviewable.io/reviews/russtedrake/manipulation/170#-MlwBgij2FygGZbKZ024:-MlwH98ZEDWSCeT1zLLW:b-e4y0cf) ([raw file](https://github.com/russtedrake/manipulation/blob/bbc6afded185ccba7d73e0f06f303a5ffbe74910/clutter.html#L858)):*
<details><summary><i>Previously, rachelholladay (Rachel Holladay) wrote…</i></summary><blockquote>

Updated! 
</blockquote></details>

will just make sure CI is happy, then merge

**Comment by RussTedrake** [comment]
i would add an `id` tag to the figure, and add a link to `href=#my_figure_id` in the problem

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/170#-:-MlwHWEO9GEAlksZDJtD:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @RussTedrake)

**Comment by rachelholladay** [comment]
> i would add an `id` tag to the figure, and add a link to `href=#my_figure_id` in the problem

Muchas gracias.

**Pull request merged**
