### PR TITLE
Chapter 4 Test Fixes

### PR DESCRIPTION
**Pull request by hjsuh94**
@mfeng9 for the record, here are the bugs that were in the previous test:
- Students would sometimes see tests succeeding and failing at random for ransac and icp. RANSAC is really random, so I've added `np.random.seed` to make the test more deterministic (always a good practice for testing that includes random)
- The ICP had a more interesting testing bug. If students forget to handle improper rotations, the following happens:
   - since the test cases written for `least_squares_transform` are based on proper rigid transforms, it never checks for handling of improper rotations. 
   - but this does matter for `icp` since there correspondences are not one-to-one and improper transforms occur. So they would get full score on `least_squares_transforms` but get points off for `icp`.  
   - There are a few lucky cases where even if they didn't handle improper rotations, they luck out and get full score for both. Again, I've added `np.random.seed` to avoid these random luck-outs.

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/48)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/48)* status: all files reviewed, 1 unresolved discussion (waiting on @hjsuh94)

___
*[manipulation/exercises/pose/test_icp.py, line 30 at r1](https://reviewable.io/reviews/russtedrake/manipulation/48#-MI-fbYY1e5Iq0iv3di7:-MI-fbYY1e5Iq0iv3di8:bx7uq94) ([raw file](https://github.com/russtedrake/manipulation/blob/c2f46153cdfb5acc48dd263edfc7bc49261a5612/manipulation/exercises/pose/test_icp.py#L30)):*
> ```Python
> 
> 
> def generate_random_transform(seed_num):
> ```

Consider using drake’s UniformlyRandomRotationMatrix instead?  

It would be the same
Ggenerator = drake.common.RandomGenerator(seed)
R = UniformlyRandomRotationMatrix(generator)

**Review by hjsuh94 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/48)* status: all files reviewed, 1 unresolved discussion (waiting on @RussTedrake)

___
*[manipulation/exercises/pose/test_icp.py, line 30 at r1](https://reviewable.io/reviews/russtedrake/manipulation/48#-MI-fbYY1e5Iq0iv3di7:-MI-kZP94sZNoDi3NIWw:blzq1u7) ([raw file](https://github.com/russtedrake/manipulation/blob/c2f46153cdfb5acc48dd263edfc7bc49261a5612/manipulation/exercises/pose/test_icp.py#L30)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Consider using drake’s UniformlyRandomRotationMatrix instead?  

It would be the same
Ggenerator = drake.common.RandomGenerator(seed)
R = UniformlyRandomRotationMatrix(generator)
</blockquote></details>

I managed to change it for Rotation, but do you know the correct syntax for how to generate a random translation? 

Seems like `generator()` gives an int, and I could get a random float if I did `generator() - generator.min() / (generator.max() - generator.min())`, but there are no bindings for `.max()` and `.min()` them in python. 

I guess we could just use `np.random.rand()` for the translations but seems somewhat repetitive?

**Comment by RussTedrake** [comment]
https://github.com/RobotLocomotion/drake/pull/14102

**Comment by hjsuh94** [comment]
Wow - did you happen to coincidentally write the PR 4 days ago? that's amazing! 

I've updated it with a new syntax.

**Review by RussTedrake — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/48)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[manipulation/exercises/pose/test_icp.py, line 30 at r1](https://reviewable.io/reviews/russtedrake/manipulation/48#-MI-fbYY1e5Iq0iv3di7:-MI1svL3-4NVlYy7nOva:b-p02ydf) ([raw file](https://github.com/russtedrake/manipulation/blob/c2f46153cdfb5acc48dd263edfc7bc49261a5612/manipulation/exercises/pose/test_icp.py#L30)):*
<details><summary><i>Previously, hjsuh94 (Hyung Ju Suh (Terry)) wrote…</i></summary><blockquote>

I managed to change it for Rotation, but do you know the correct syntax for how to generate a random translation? 

Seems like `generator()` gives an int, and I could get a random float if I did `generator() - generator.min() / (generator.max() - generator.min())`, but there are no bindings for `.max()` and `.min()` them in python. 

I guess we could just use `np.random.rand()` for the translations but seems somewhat repetitive?
</blockquote></details>

this looks right to me now.  thanks.

**Pull request merged**
