### PR TITLE
attempt to fix ubuntu and mac CI

### PR DESCRIPTION
**Pull request by RussTedrake**
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/manipulation/94)

### CODE REVIEW

**Comment by RussTedrake** [comment]
fyi @jamiesnape (cc @jwnimmer-tri)
These steps would presumably fix drake's mac ci, too... but it would require `pip` installing `scipy`, and we've so far avoided any pip install for drake.
(the last test failure on mac is a flake that we saw before homebrew caught fire.  we'll still have to fix that, but all of the interesting failures are resolved now).

**Comment by jwnimmer-tri** [comment]
> ... and we've so far avoided any pip install for drake.

Not completely accurate.  On macOS, we do use pip:

https://github.com/RobotLocomotion/drake/blob/432c8dbce18d36ef78245eea8c3acc3c5b5dbed7/setup/mac/binary_distribution/install_prereqs.sh#L29

https://github.com/RobotLocomotion/drake/blob/432c8dbce18d36ef78245eea8c3acc3c5b5dbed7/setup/mac/source_distribution/install_prereqs.sh#L69-L70

Drake currently does use homebrew (not pip) for `scipy`, though -- I think because it's such a large (slow) beast to install via pip.

**Comment by RussTedrake** [comment]
i actually think we shouldn't have `scipy` as a dependency at all, last i checked it was used only in `planar_scenegraph_visualizer`.  but last I checked, drake's mac CI was broken because homebrew bumped scipy to python 3.9 (that was breaking me here, too).  moving the scipy to pip is perhaps a short-term workaround.

**Comment by jamiesnape** [comment]
There are a couple of uses in drake, and theoretically some in drake-visualizer. As far as drake goes, I think it would be good to lose the dependency (and not amazingly difficult) and not really sure if anyone actually uses the fewnfeatures in drake-visualizer that need scipy.

**Comment by jamiesnape** [comment]
Historically the main issue was a conflict between the pip and Homebrew `f2py` binaries in NumPy.

**Pull request merged**
