### PR TITLE
Added cameras to spot model

### PR DESCRIPTION
**Pull request by wrangelvid**
This adds a scenario file with camera configurations for Spot and the script used to extract those intrinsics.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/269)

### CODE REVIEW

**Review by RussTedrake — COMMENTED** [review]
Thanks for this!   a few minor requests. 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/269#-:-NjZJ7Vf-lwk38QzL9GH:bubp8pa)* status: all files reviewed, 2 unresolved discussions (waiting on @wrangelvid)

___
*[`manipulation/models/spot/populate_model_with_camera_intrinsics.py` line 150 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/269#-NjZHfnh6WQs3MKU4QOO:-NjZHfnh6WQs3MKU4QOP:bpny1dw) ([raw file](https://github.com/RussTedrake/manipulation/blob/e2349e6765f8f9ef4ea9cabe60a6b254f9fd612d/manipulation/models/spot/populate_model_with_camera_intrinsics.py#L150)):*
> ```Python
>         {**spot_with_arm_data, **{"cameras": camera_configs}},
>         filename=options.output_scenario_file,
>     )
> ```

this could rewrite / reshuffle / loose comments, etc.  i would think it's better to just cat the results on the end of the existing text file?  Perhaps this method should only ever just output the camera text (to the screen?) and let users paste it into the scenarios manually?
___
*[`manipulation/models/spot/spot_with_arm_and_cameras.scenario.yaml` line 1 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/269#-NjZI-kUClMv3SwRXzvT:-NjZI-kUClMv3SwRXzvU:b6o8h7b) ([raw file](https://github.com/RussTedrake/manipulation/blob/e2349e6765f8f9ef4ea9cabe60a6b254f9fd612d/manipulation/models/spot/spot_with_arm_and_cameras.scenario.yaml#L1)):*
> ```YAML
> cameras:
> ```

i think we should just add the cameras directly to (the end of) spot_with_arm.  No need to fork yet another scenario.

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/269)* status: all files reviewed, 3 unresolved discussions (waiting on @wrangelvid)

___
*[`manipulation/models/spot/populate_model_with_camera_intrinsics.py` line 38 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/269#-NjZJU0B9Q-Yxd7POwi8:-NjZJU0B9Q-Yxd7POwi9:b-p7dobc) ([raw file](https://github.com/RussTedrake/manipulation/blob/e2349e6765f8f9ef4ea9cabe60a6b254f9fd612d/manipulation/models/spot/populate_model_with_camera_intrinsics.py#L38)):*
> ```Python
>         "--output-scenario-file",
>         help="The desired output filename",
>         default="./spot_with_arm_and_cameras.scenario.yaml",
> ```

btw -- strange that you have the floating base as default above, but not here.

**Comment by RussTedrake** [comment]
*[`mobile/spot.ipynb` line 128 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/269#-NjZK4wP19boYzmDSUN9:-NjZK4wP19boYzmDSUNA:b67z6ro) ([raw file](https://github.com/RussTedrake/manipulation/blob/e2349e6765f8f9ef4ea9cabe60a6b254f9fd612d/mobile/spot.ipynb#L128)):*
> ```
>    "metadata": {},
>    "source": [
>     "You can also load the model with cameras."
> ```

i would zap this..  since we should just have the main model have cameras.  (they cost effectively nothing if they are not evaluated)

**Review by wrangelvid — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/269)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @RussTedrake)

___
*[`manipulation/models/spot/spot_with_arm_and_cameras.scenario.yaml` line 1 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/269#-NjZI-kUClMv3SwRXzvT:-Njd7jus4mGH32n_bp9G:b-896fix) ([raw file](https://github.com/RussTedrake/manipulation/blob/e2349e6765f8f9ef4ea9cabe60a6b254f9fd612d/manipulation/models/spot/spot_with_arm_and_cameras.scenario.yaml#L1)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i think we should just add the cameras directly to (the end of) spot_with_arm.  No need to fork yet another scenario.
</blockquote></details>

Done.
___
*[`mobile/spot.ipynb` line 128 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/269#-NjZK4wP19boYzmDSUN9:-Njd7io63zzNnh6h7S86:b-896fix) ([raw file](https://github.com/RussTedrake/manipulation/blob/e2349e6765f8f9ef4ea9cabe60a6b254f9fd612d/mobile/spot.ipynb#L128)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

i would zap this..  since we should just have the main model have cameras.  (they cost effectively nothing if they are not evaluated)
</blockquote></details>

Done.
___
*[`manipulation/models/spot/populate_model_with_camera_intrinsics.py` line 150 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/269#-NjZHfnh6WQs3MKU4QOO:-NjdDRYgEBasMMdQhoQN:b-vwsdlg) ([raw file](https://github.com/RussTedrake/manipulation/blob/e2349e6765f8f9ef4ea9cabe60a6b254f9fd612d/manipulation/models/spot/populate_model_with_camera_intrinsics.py#L150)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

this could rewrite / reshuffle / loose comments, etc.  i would think it's better to just cat the results on the end of the existing text file?  Perhaps this method should only ever just output the camera text (to the screen?) and let users paste it into the scenarios manually?
</blockquote></details>

I like the idea. However, I couldn't get drake's yaml_dump to not reshuffle the dictionary.

**Review by RussTedrake — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wrangelvid)

**Pull request merged**
