### PR TITLE
Visualize robot positions in HardwareStationInterface

### PR DESCRIPTION
**Pull request by siddancha**
## Problem

Slack thread: https://drakedevelopers.slack.com/archives/C2CK4CWE7/p1720146312718089

When using `MakeHardwareStation(meshcat, hardware=True)` , `_MakeHardwareStationInterface(meshcat)` completely ignores its meschat. However, a strong use-case when running real robot hardware is to run Meshcat and visualize robot positions.

It seems that a (partial) solution was previously implemented, but was commented out.

## Solution

**Philosophy:** When the user passes a meshcat instance when running on real hardware, we assume that the user wants to visualize robot positions using this instance. In this case, the relevant systems are added to the station and wired appropriately (see below). When `meshcat=None`, these are not added.

- [x] Un-commented the partial solution. The partial solution adds a `SceneGraph`, `MultibodyPositionToGeometryPose` and runs `ApplyVisualizationConfig()`. However, `MultibodyPositionToGeometryPose` is not wired.
- [x] Wired output positions from `IiwaStatusReceiver` and/or `SchunkWsgStatusReceiver` to the `MultibodyPositionToGeometryPose`. This allows the user to successfully visualize the plant in Meshcat.
- [x] Added a test to check that `MakeHardwareStation(hardware=True)` works with and without meshcat. 

## System diagrams
The following system diagrams were generated from `manipulation/test/test_hardware_station_interface.py`:

<br>

<figure align="center">
  
  <p align="center"><i>HardwareStationInterface when <code>meshcat=None</code></i></p>
</figure>

<br>

<figure align="center">
  
  <p align="center"><i>HardwareStationInterface when a meshcat instance is passed by the user</i></p>
</figure>

- - -
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324)

### CODE REVIEW

**Review by RussTedrake — APPROVED** [review]
I don't by the documented argument for nesting the class.  But otherwise

:lgtm:  

Thank you for pushing these upstream (and writing beautiful code).

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324#-:-O1fZk8rA_2ZHFkv5KKz:b-1dnarq)* status: all files reviewed, 2 unresolved discussions (waiting on @siddancha)

___
*[`manipulation/station.py` line 1255 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fXy19DeszcGnLbr_1:-O1fXy19DeszcGnLbr_2:b-qgi1wo) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1255)):*
> ```Python
> 
>     # We define the class inside the function because the number of input ports
>     # depends on the number of model instances.
> ```

why does that necessitate being inside a function?  you can just pass the necessary arguments into the constructor?
___
*[`manipulation/station.py` line 1398 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fYgTnELCMCsGM0zVf:-O1fYgTnELCMCsGM0zVg:b38vgux) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1398)):*
> ```Python
>             config,
>             builder=builder,
>             plant=plant,
> ```

btw -- it's too bad that we have to pass the plant in here. for this visualization config, it think it should not be needed.  but according to the drake docs, I agree with you that it's necessary.

fyi @jwnimmer-tri.
(in the implementation of ApplyVisualizationConfigImpl, plant it only used for publishing contact results and inertias).

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @RussTedrake and @siddancha)

___
*[`manipulation/station.py` line 1398 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fYgTnELCMCsGM0zVf:-O1gbHDREJ1f1Jv3iR9L:b-8o8ib9) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1398)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- it's too bad that we have to pass the plant in here. for this visualization config, it think it should not be needed.  but according to the drake docs, I agree with you that it's necessary.

fyi @jwnimmer-tri.
(in the implementation of ApplyVisualizationConfigImpl, plant it only used for publishing contact results and inertias).
</blockquote></details>

If the only thing you're publishing is illustration, then you could choose to call `MeshcatVisualizer.AddToBuilder` instead of `ApplyVisualizationConfig`.  In that design, the plant reference is not necessary.

`ApplyVisualizationConfig` is syntactic sugar for common use cases.  It's OK to set it aside if it doesn't meet the need, especially when you're not actually providing your users access to the `config` object to tweak anyway.

**Review by siddancha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`manipulation/station.py` line 1255 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fXy19DeszcGnLbr_1:-O1gbB1v4AmpY9I1YXbZ:b957du5) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1255)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

why does that necessitate being inside a function?  you can just pass the necessary arguments into the constructor?
</blockquote></details>

My bad -- you're right! That comment was incorrect and I've now removed it.

Would you prefer having `ConcatenatePositions` defined outside the function with constructor arguments? Here's what it would look like: https://github.com/siddancha/manipulation/blob/9b18aa4226fbbeb1570267678e85b14f0b545c8d/manipulation/station.py#L1247-L1302
___
*[`manipulation/station.py` line 1398 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fYgTnELCMCsGM0zVf:-O1gcN0dCM80OUXXO0WC:b-yrdbg4) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1398)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If the only thing you're publishing is illustration, then you could choose to call `MeshcatVisualizer.AddToBuilder` instead of `ApplyVisualizationConfig`.  In that design, the plant reference is not necessary.

`ApplyVisualizationConfig` is syntactic sugar for common use cases.  It's OK to set it aside if it doesn't meet the need, especially when you're not actually providing your users access to the `config` object to tweak anyway.
</blockquote></details>

Makes sense! I can confirm that I've tried using `MeshcatVisualizer` instead of `ApplyVisualizationConfig` and it works well for me! What this doesn't do is add `DrakeVisualizer` systems that I don't need anyway.

**Review by siddancha — COMMENTED** [review]
I moved `ConcatenateVectors` outside the function with constructor args, and followed Jeremy's suggestion to replace `ApplyVisualizationConfig()` with `MeshcatVisualizer.AddToBuilder()` (which slightly simplifies the diagram).

I think we're ready to merge.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324#-:-O1qydL51kaV67_y5CCK:b7phdgj)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`manipulation/station.py` line 1255 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fXy19DeszcGnLbr_1:-O1qy7CJ50TsffDu_3_p:beu4k3q) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1255)):*
<details><summary><i>Previously, siddancha (Siddharth Ancha) wrote…</i></summary><blockquote>

My bad -- you're right! That comment was incorrect and I've now removed it.

Would you prefer having `ConcatenatePositions` defined outside the function with constructor arguments? Here's what it would look like: https://github.com/siddancha/manipulation/blob/9b18aa4226fbbeb1570267678e85b14f0b545c8d/manipulation/station.py#L1247-L1302
</blockquote></details>

Moved `ConcatenateVectors` outside the function with constructor args.
___
*[`manipulation/station.py` line 1398 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fYgTnELCMCsGM0zVf:-O1qyH1738XxL8XZ-Ghr:bjoy0f4) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1398)):*
<details><summary><i>Previously, siddancha (Siddharth Ancha) wrote…</i></summary><blockquote>

Makes sense! I can confirm that I've tried using `MeshcatVisualizer` instead of `ApplyVisualizationConfig` and it works well for me! What this doesn't do is add `DrakeVisualizer` systems that I don't need anyway.
</blockquote></details>

Commented out `ApplyVisualizationConfig()`and replaced it with `MeshcatVisualizer.AddToBuilder()`. Now, the system diagram is a bit simpler.

**Review by RussTedrake — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324)* status: all files reviewed, 1 unresolved discussion (waiting on @jwnimmer-tri and @siddancha)

___
*[`manipulation/station.py` line 1398 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fYgTnELCMCsGM0zVf:-O1wN3uu7uyhpZDpwjx5:bj7ra6s) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1398)):*
<details><summary><i>Previously, siddancha (Siddharth Ancha) wrote…</i></summary><blockquote>

Commented out `ApplyVisualizationConfig()`and replaced it with `MeshcatVisualizer.AddToBuilder()`. Now, the system diagram is a bit simpler.


</blockquote></details>

of course you could publish both collision and visual geometry by adding the two MeshcatVisualizers (that's what was happening before). do we think the collision / visual geometry option is less relevant for the hardware version?

**Review by siddancha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @RussTedrake)

___
*[`manipulation/station.py` line 1398 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/324#-O1fYgTnELCMCsGM0zVf:-O1xBFsoAacXMnE2l2IV:b9m9625) ([raw file](https://github.com/RussTedrake/manipulation/blob/78c66a30986914b1e71875f7361c9d0a56ea2a54/manipulation/station.py#L1398)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

of course you could publish both collision and visual geometry by adding the two MeshcatVisualizers (that's what was happening before). do we think the collision / visual geometry option is less relevant for the hardware version?
</blockquote></details>

I think collision geometries are indeed useful in the hardware version. Reverting back to `ApplyVisualizationConfig()`.

I think it's fine if `ApplyVisualizationConfig()` takes the plant as an argument but doesn't use it. At least it provides a comprehensive set of visualization options that one day we might let the user tweak.

**Review by RussTedrake — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/324)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siddancha)

**Pull request merged**
