### PR TITLE
add MultibodyPositionToBodyPose …

### PR DESCRIPTION
**Pull request by RussTedrake**
and purge last use of the 'cheat ports' in the intro and suction notebooks

- - -
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/284)

### CODE REVIEW

**Review by nepfaff — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/284)* status: all files reviewed, 1 unresolved discussion (waiting on @RussTedrake)

___
*[`manipulation/systems.py` line 73 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/284#-Nn49XA557NA83Uy3fH9:-Nn49XA557NA83Uy3fHA:bph61hg) ([raw file](https://github.com/RussTedrake/manipulation/blob/bbaad58756164e06a2952523b70db1d2457e2beb/manipulation/systems.py#L73)):*
> ```Python
>         )
> 
>     def _CalcOutput(self, context, output):
> ```

What are your manipulation naming conventions? I'm guessing the camel case is for compatibility with Drake's C++ function names. When should we stick to Python's snake case, and when to C++'s camel case?

**Comment by RussTedrake** [comment]
*[`manipulation/systems.py` line 73 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/284#-Nn49XA557NA83Uy3fH9:-Nn4BX9b2XYl8pPyYov6:bg0je2o) ([raw file](https://github.com/RussTedrake/manipulation/blob/bbaad58756164e06a2952523b70db1d2457e2beb/manipulation/systems.py#L73)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

What are your manipulation naming conventions? I'm guessing the camel case is for compatibility with Drake's C++ function names. When should we stick to Python's snake case, and when to C++'s camel case?
</blockquote></details>

I think we should use https://drake.mit.edu/code_style_guide.html

**Review by nepfaff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/284)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @RussTedrake)

___
*[`manipulation/systems.py` line 73 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/284#-Nn49XA557NA83Uy3fH9:-Nn4VEcFDJMy80Y5VDjJ:b-o3qmhy) ([raw file](https://github.com/RussTedrake/manipulation/blob/bbaad58756164e06a2952523b70db1d2457e2beb/manipulation/systems.py#L73)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

I think we should use https://drake.mit.edu/code_style_guide.html
</blockquote></details>

Sticking to Drake's C++ style guide for Python code as discussed over Slack

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/284)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @nepfaff)

___
*[`manipulation/systems.py` line 73 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/284#-Nn49XA557NA83Uy3fH9:-Nn4b7aCC-23vP9ZZKjY:b-896fix) ([raw file](https://github.com/RussTedrake/manipulation/blob/bbaad58756164e06a2952523b70db1d2457e2beb/manipulation/systems.py#L73)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

Sticking to Drake's C++ style guide for Python code as discussed over Slack
</blockquote></details>

Done.

**Pull request merged**
