### PR TITLE
Problem Set 7 Fixes

### PR DESCRIPTION
**Pull request by ryangpeixu**
This change is [Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)

### CODE REVIEW

**Review by nepfaff — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)* status: all files reviewed, 2 unresolved discussions (waiting on @ryangpeixu)

___
*[`book/force.html` line 1105 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9GJyu20P_anelDOWaI:-O9GJyu20P_anelDOWaJ:bmk2ktk) ([raw file](https://github.com/RussTedrake/manipulation/blob/2ea444168441228f3f81024645e0af295e094932/book/force.html#L1105)):*
> ```HTML
>         <li> If we push too hard (i.e. $f^{C}_{finger,z}$ is too big), then
>         the pivot point will slide to the left. First, balance forces along the 
>         horizontal axis to derive an upper bound for $f^{C}_{finger, z}$.
> ```

You no longer specify the variables that this should be a function of. Is this intentional? 
___
*[`book/force.html` line 1106 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9GOIze3bBEA_UldfAx:-O9GOIzfBJr2qxHfi6dA:b86nrdq) ([raw file](https://github.com/RussTedrake/manipulation/blob/2ea444168441228f3f81024645e0af295e094932/book/force.html#L1106)):*
> ```HTML
>         the pivot point will slide to the left. First, balance forces along the 
>         horizontal axis to derive an upper bound for $f^{C}_{finger, z}$.
>         Then, balance forces along the y-axis to derive another upper bound for $f^{C}_{finger,z}$.
> ```

This seems confusing to me. From my understanding, we aren't deriving "another" lower bound. We are simply using this to solve for the unknowns in the single lower bound that we started deriving using the first balance equation.

If I understand this correctly, it might be clearer to have a hint that mentions using both horizontal and vertical force balance equations and combining that with the solution from part a) to obtain the normal force upper bound.

**Review by ryangpeixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)* status: all files reviewed, 2 unresolved discussions (waiting on @nepfaff)

___
*[`book/force.html` line 1105 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9GJyu20P_anelDOWaI:-O9MlVueEsIOXzqRG1Go:bo5gpvl) ([raw file](https://github.com/RussTedrake/manipulation/blob/2ea444168441228f3f81024645e0af295e094932/book/force.html#L1105)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

You no longer specify the variables that this should be a function of. Is this intentional?
</blockquote></details>

The solution has several steps that are not the most clearly motivated. I think there was a note from last year that this problem could be simplified or provided more guidance. The first uppper bound shouldn't use just the variables given in the old problem statement as we are still finding relations between the variables to substitute into.
___
*[`book/force.html` line 1106 at r1](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9GOIze3bBEA_UldfAx:-O9MmnDp1fo5foMDsrYx:b-c90pc2) ([raw file](https://github.com/RussTedrake/manipulation/blob/2ea444168441228f3f81024645e0af295e094932/book/force.html#L1106)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

This seems confusing to me. From my understanding, we aren't deriving "another" lower bound. We are simply using this to solve for the unknowns in the single lower bound that we started deriving using the first balance equation.

If I understand this correctly, it might be clearer to have a hint that mentions using both horizontal and vertical force balance equations and combining that with the solution from part a) to obtain the normal force upper bound.
</blockquote></details>

Agreed - will change that now!

**Review by nepfaff — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @ryangpeixu)

___
*[`book/force.html` line 1106 at r2](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9ogFrR8WTcrSoEIcEt:-O9ogFrR8WTcrSoEIcEu:bqn6qca) ([raw file](https://github.com/RussTedrake/manipulation/blob/5fe2a66d116c4315477fd024bcdf633dee4cba1b/book/force.html#L1106)):*
> ```HTML
>         the pivot point will slide to the left. First, balance forces along the 
>         horizontal axis to derive an upper bound for $f^{C}_{finger, z}$.
>         Then, balance forces along the y-axis an equation with $f^{C}_{finger,z}$.
> ```

I don't quite get the sentence here. Do you mean "along the y-axis to obtain an equation"?
___
*[`book/force/exercises/hybrid_force_position.ipynb` line 321 at r2](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9ofonC0IJ9T5McPLc8:-O9ofonC0IJ9T5McPLc9:b-fbk8e2) ([raw file](https://github.com/RussTedrake/manipulation/blob/5fe2a66d116c4315477fd024bcdf633dee4cba1b/book/force/exercises/hybrid_force_position.ipynb#L321)):*
> ```
>    },
>    "source": [
>     "#### **Problem 9.3.d** [4pts] Below, you will write a function `compute_ctrl` that implements a feedback policy which computes spatial forces $u=[\\tau_y,f_x,f_z]$ upon given current and desired position along the $x,\\theta_y$ direction, while achieving desired forces along the $z$ direction. \n",
> ```

Should we reduce the number of points now that we removed the gain tuning part? Maybe 2 points is more appropriate?
___
*[`book/force/exercises/hybrid_force_position.ipynb` line 394 at r2](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9og2b24zYP02VfNr7l:-O9og2b3E6trguIxjBqR:b-dldib3) ([raw file](https://github.com/RussTedrake/manipulation/blob/5fe2a66d116c4315477fd024bcdf633dee4cba1b/book/force/exercises/hybrid_force_position.ipynb#L394)):*
> ```
>     "# NOTE: you may tune the velocity and duration to achieve the above specification.\n",
>     "velocity = -0.125  # p_des = 0.65 + velocity * max\\{time - 2.0, 0\\}\n",
>     "duration = 0.1  # duration to simulate. We check the book pose at the end of duration. set to 5~10.\n",
> ```

Similar to the gains, we should set a reasonable default value here and modify the comment appropriately

**Review by ryangpeixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @nepfaff)

___
*[`book/force.html` line 1106 at r2](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9ogFrR8WTcrSoEIcEt:-O9pse9UDeZG1xaKZHM4:b-kngg8q) ([raw file](https://github.com/RussTedrake/manipulation/blob/5fe2a66d116c4315477fd024bcdf633dee4cba1b/book/force.html#L1106)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

I don't quite get the sentence here. Do you mean "along the y-axis to obtain an equation"?
</blockquote></details>

Oh yeah, thanks for catching that!
___
*[`book/force/exercises/hybrid_force_position.ipynb` line 321 at r2](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9ofonC0IJ9T5McPLc8:-O9praxU1dzeEjMoTNvE:b-5dzefe) ([raw file](https://github.com/RussTedrake/manipulation/blob/5fe2a66d116c4315477fd024bcdf633dee4cba1b/book/force/exercises/hybrid_force_position.ipynb#L321)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

Should we reduce the number of points now that we removed the gain tuning part? Maybe 2 points is more appropriate?
</blockquote></details>

Yep, agreed!
___
*[`book/force/exercises/hybrid_force_position.ipynb` line 394 at r2](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9og2b24zYP02VfNr7l:-O9pwUVzDxTelLD2T7fS:b-qy7su4) ([raw file](https://github.com/RussTedrake/manipulation/blob/5fe2a66d116c4315477fd024bcdf633dee4cba1b/book/force/exercises/hybrid_force_position.ipynb#L394)):*
<details><summary><i>Previously, nepfaff (Nicholas Pfaff) wrote…</i></summary><blockquote>

Similar to the gains, we should set a reasonable default value here and modify the comment appropriately
</blockquote></details>

Added!

**Review by nepfaff — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ryangpeixu)

**Review by nepfaff — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)* status: all files reviewed, 1 unresolved discussion (waiting on @ryangpeixu)

___
*[`book/force/exercises/hybrid_force_position.ipynb` line 321 at r4](https://reviewable.io/reviews/RussTedrake/manipulation/372#-O9qtbRA0AO9cRWiGv5e:-O9qtbRA0AO9cRWiGv5f:bxyxojl) ([raw file](https://github.com/RussTedrake/manipulation/blob/66bab66ceb1b9b3652ffafd178bd3ae3baad3630/book/force/exercises/hybrid_force_position.ipynb#L321)):*
> ```
>    },
>    "source": [
>     "#### **Problem 9.3.d** [2pts] Below, you will write a function `compute_ctrl` that implements a feedback policy which computes spatial forces $u=[\\tau_y,f_x,f_z]$ upon given current and desired position along the $x,\\theta_y$ direction, while achieving desired forces along the $z$ direction. \n",
> ```

Just noticed that you will also need to change that (the number of points) in the autograder (`test_hybrid.py`)

**Review by nepfaff — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/372)* status: all files reviewed, 1 unresolved discussion (waiting on @ryangpeixu)

**Pull request merged**
